spring.application.name=miniProject

# Server Port
server.port=8080

# MongoDB Atlas Connection String
spring.data.mongodb.uri=mongodb+srv://tushararya773_db_user:aCPhJvpLXQOBNndo@cluster0.5bdhlkq.mongodb.net/miniProject?retryWrites=true&w=majority&appName=Cluster0

# Disable auto-configuration of Spring Security default user
spring.security.user.name=admin
spring.security.user.password=admin
