spring.application.name=miniProject
# MongoDB Atlas Connection String - Please replace <db_password> with your actual password
spring.data.mongodb.uri=mongodb+srv://tushararya773_db_user:aCPhJvpLXQOBNndo@cluster0.5bdhlkq.mongodb.net/miniProject?retryWrites=true&w=majority&appName=Cluster0
